# Generated by Django 4.0.1 on 2022-01-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=40)),
                ('peso', models.FloatField()),
                ('estatura', models.FloatField()),
                ('fuma', models.BooleanField()),
                ('añosfumando', models.IntegerField()),
                ('dieta', models.BooleanField()),
                ('rpe', models.FloatField()),
                ('estado', models.BooleanField()),
                ('prioridad', models.FloatField()),
                ('riesgo', models.FloatField()),
            ],
        ),
    ]
